name: Citadel
version: '${version}'
main: org.trackedout.citadel.Citadel
api-version: 1.20
author: trackedout
depend: [ InventoryFramework, WorldGuard ]
load: POSTWORLD
website: "https://github.com/trackedout/citadel"
description: The Citadel plugin
