/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.trackedout.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param name 
 * @param player 
 * @param server 
 * @param x 
 * @param y 
 * @param z 
 * @param count 
 * @param sourceIP 
 */


data class EventsPostRequest (

    @Json(name = "name")
    val name: kotlin.String,

    @Json(name = "player")
    val player: kotlin.String,

    @Json(name = "server")
    val server: kotlin.String,

    @Json(name = "x")
    val x: kotlin.Double,

    @Json(name = "y")
    val y: kotlin.Double,

    @Json(name = "z")
    val z: kotlin.Double,

    @Json(name = "count")
    val count: kotlin.Int = 1,

    @Json(name = "sourceIP")
    val sourceIP: kotlin.String? = null

)

